### ISSUE TITLE
Question texts can be too long

### ISSUE THREAD

**Issue by ywarnecke** [imi-ms/MoPat#8]
If the question text is too long, it can cause a Mysql exception: 

<pre>
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'question_text' at row 1
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:909)
    ... 120 common frames omitted
</pre>

This should be validated. 

This is probably valid for all freetext fields

**Comment by ywarnecke** [comment]
Implemented character limit validation for all free-text fields (including question descriptions) set to 2000 characters.

*   **Backend**: Validation logic strips HTML tags before calculating length to ensure the limit applies to the actual visible text content, preventing `MysqlDataTruncation` exceptions.
*   **Frontend**: Added real-time character count and error notifications to alert users when the limit is exceeded.

Merged in #322
